const express = require('express');
const router  = express.Router();

const authRoutes          = require('./auth.routes');
const userRoutes          = require('./user.routes');
const bannerRoutes        = require('./banner.routes');
const mediaRoutes         = require('./media.routes');
const folderRoutes        = require('./folder.routes');
const categoryRoutes      = require('./category.routes');
const brandRoutes         = require('./brand.routes');
const productRoutes       = require('./product.routes');
const productVariantRoutes = require('./productVariant.routes');
const couponRoutes        = require('./coupon.routes');
const promotionRoutes     = require('./promotion.routes');
const giftProgramRoutes   = require('./gift-program.routes');
const tagRoutes           = require('./tag.routes');
const blogCategoryRoutes  = require('./blogCategory.routes');
const blogPostRoutes      = require('./blogPost.routes');
const flashSaleRoutes     = require('./flashSale.routes');
const dashboardRoutes     = require('./dashboard.routes');
const menuRoutes          = require('./menu.routes');
const roleRoutes          = require('./role.routes');
const supplierRoutes      = require('./supplier.routes');
const purchaseOrderRoutes = require('./purchaseOrder.routes');
const stockExportRoutes   = require('./stockExport.routes');
const stockAuditRoutes    = require('./stockAudit.routes');
const stockMovementRoutes = require('./stockMovement.routes');
const purchaseReturnRoutes = require('./purchaseReturn.routes');
const stockAlertRoutes    = require('./stockAlert.routes');
const stockDocumentRoutes = require('./stockDocument.routes');
const inventoryReportRoutes = require('./inventoryReport.routes');
const stockReceivingRoutes = require('./stockReceiving.routes');
const auditLogRoutes      = require('./auditLog.routes');
const searchRoutes        = require('./search.routes');
const recommendationRoutes = require('./recommendation.routes');
const chatbotRoutes        = require('./chatbot.routes');
const upsellRoutes         = require('./upsell.routes');

router.use('/auth',             authRoutes);
router.use('/users',            userRoutes);
router.use('/banners',          bannerRoutes);
router.use('/media',            mediaRoutes);
router.use('/folders',          folderRoutes);
router.use('/categories',       categoryRoutes);
router.use('/brands',           brandRoutes);
router.use('/products',         productRoutes);
router.use('/product-variants', productVariantRoutes);
router.use('/coupons',          couponRoutes);
router.use('/promotions',       promotionRoutes);
router.use('/gift-programs',    giftProgramRoutes);
router.use('/flash-sales',       flashSaleRoutes);
router.use('/dashboard',         dashboardRoutes);
router.use('/tags',             tagRoutes);
router.use('/blog-categories',  blogCategoryRoutes);
router.use('/blog-posts',       blogPostRoutes);
router.use('/menus',            menuRoutes);
router.use('/roles',            roleRoutes);
router.use('/suppliers',        supplierRoutes);
router.use('/purchase-orders',  purchaseOrderRoutes);
router.use('/stock-exports',    stockExportRoutes);
router.use('/stock-audits',     stockAuditRoutes);
router.use('/stock-movements',  stockMovementRoutes);
router.use('/purchase-returns', purchaseReturnRoutes);
router.use('/stock-alerts',     stockAlertRoutes);
router.use('/stock-documents',  stockDocumentRoutes);
router.use('/inventory-reports', inventoryReportRoutes);
router.use('/stock-receivings', stockReceivingRoutes);
router.use('/audit-logs',       auditLogRoutes);
router.use('/search',           searchRoutes);
router.use('/recommendations',  recommendationRoutes);
router.use('/chat',             chatbotRoutes);
router.use('/upsell',           upsellRoutes);

module.exports = router;
