const express = require('express');
const router  = express.Router();

const authRoutes          = require('./auth.routes');
const userRoutes          = require('./user.routes');
const bannerRoutes        = require('./banner.routes');
const mediaRoutes         = require('./media.routes');
const folderRoutes        = require('./folder.routes');
const categoryRoutes      = require('./category.routes');
const brandRoutes         = require('./brand.routes');
const productRoutes       = require('./product.routes');
const productVariantRoutes = require('./productVariant.routes');
const couponRoutes        = require('./coupon.routes');
const promotionRoutes     = require('./promotion.routes');
const giftProgramRoutes   = require('./gift-program.routes');
const tagRoutes           = require('./tag.routes');
const blogCategoryRoutes  = require('./blogCategory.routes');
const blogPostRoutes      = require('./blogPost.routes');
const flashSaleRoutes     = require('./flashSale.routes');
const dashboardRoutes     = require('./dashboard.routes');

router.use('/auth',             authRoutes);
router.use('/users',            userRoutes);
router.use('/banners',          bannerRoutes);
router.use('/media',            mediaRoutes);
router.use('/folders',          folderRoutes);
router.use('/categories',       categoryRoutes);
router.use('/brands',           brandRoutes);
router.use('/products',         productRoutes);
router.use('/product-variants', productVariantRoutes);
router.use('/coupons',          couponRoutes);
router.use('/promotions',       promotionRoutes);
router.use('/gift-programs',    giftProgramRoutes);
router.use('/flash-sales',       flashSaleRoutes);
router.use('/dashboard',         dashboardRoutes);
router.use('/tags',             tagRoutes);
router.use('/blog-categories',  blogCategoryRoutes);
router.use('/blog-posts',       blogPostRoutes);

module.exports = router;
